spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://172.20.10.50:3306/mydata
    username: root
    password: b787

mybatis:
  mapper-locations: classpath:static/mapper/*.xml