spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://192.168.50.201:3306/mydata
    username: root
    password: DB_PASSWORD

mybatis:
  mapper-locations: classpath:static/mapper/*.xml