apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps
        image: wcg0112/myapps:0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred

#PLZ22
