apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: myapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps
        image: wcg0112/myapps:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
