apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps
        image: wcg0112/myapps:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred

#PLZ LAST
